# Generated by Django 2.1.5 on 2019-02-10 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_post_home'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post_home',
            name='post_ptr',
        ),
        migrations.DeleteModel(
            name='Post_home',
        ),
    ]
